### ISSUE TITLE
! could not fetch remote https://github.com/Jordan-Gilliam/ai-template

### ISSUE THREAD

**Issue by ea2399** [Jordan-Gilliam/ai-template#1]
C:\WINDOWS\system32>npx degit Jordan-Gilliam/ai-template ai-template
! could not fetch remote https://github.com/Jordan-Gilliam/ai-template
! could not find commit hash for HEAD

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Jordan-Gilliam** [comment]
Fixed. Try `npx degit https://github.com/Jordan-Gilliam/ai-template temp`
