### ISSUE TITLE
Successful compilation but error once localhost is loaded 

### ISSUE THREAD

**Issue by vcpandya** [Jordan-Gilliam/ai-template#5]
PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0
error [Error: PineconeClient: Project name not set. Call init() first.]
error - [Error: Failed to fetch Pinecone namespaces

**Comment by Jordan-Gilliam** [comment]
Are you still getting this error? I updated the README. Make sure you are configuring Pinecone correctly.

**Comment by vcpandya** [comment]
> Are you still getting this error? I updated the README. Make sure you are configuring Pinecone correctly.

Now it works but even after taking Pinecone information in .env file why do we need to enter namespace information again on the frontend?

**Comment by Jordan-Gilliam** [comment]
Namespace is different than Index. The idea is that you might create one namespace for one set of embeddings and another namespace for a different set of embeddings.
